/*
 * KYC API Public
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.kyc.java_client.api;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.junit.Assert;
import org.junit.Test;

import com.swift.kyc.java_client.ApiException;
import com.swift.kyc.java_client.model.EntityList;
import com.swift.kyc.java_client.model.ListOfCounterparties;

/**
 * API tests for ConsumptionApi
 */

public class ConsumptionApiTest {

    ConsumptionApi api = mock(ConsumptionApi.class);

    
    /**
     * Get My Counterparties
     *
     * This API is a list retrieval query that enables you to extract a list of all counterparties which granted access to your KYC group. Triggering this API will activate/re-activate the passive relationships.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void counterpartiesMyGetTest() throws ApiException {
    	ListOfCounterparties mock_ApiResponse = mock(ListOfCounterparties.class);
        when(api.counterpartiesMyGet()).thenReturn(mock_ApiResponse);
        Assert.assertEquals(api.counterpartiesMyGet(),mock_ApiResponse);
        System.out.println("Passed Test counterpartiesMyGetTest");
    }
    
        
    /**
     * Get My Entities
     *
     * This API is a list retrieval query that enables you to extract a list of all entities which belong to your KYC group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void entitiesMyGetTest() throws ApiException {
    	EntityList mock_ApiResponse = mock(EntityList.class);
        when(api.entitiesMyGet()).thenReturn(mock_ApiResponse);
        Assert.assertEquals(api.entitiesMyGet(),mock_ApiResponse);
        System.out.println("Passed Test entitiesMyGetTest");
    }
    
    
    
}
